on:
  workflow_dispatch:  // desencadenar flujo manual
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
