name: A workflow for my Hello World file
on: push
jobs: 
  name: Hello world action
  runs-on: ubuntu-lastest
  steps: 
  - uses: actions/checkout@v1
  - uses: ./action-a
  with: 
    MY_NAME: "Mona"
  
